[options]
db_host = False
db_port = False
db_user = amir
db_password = admin
db_name = odoo18_sgo_football_dev
addons_path = /home/amir/erpProject/odoo/odoo/addons,/home/amir/erpProject/odoo/addons,/home/amir/erpProject/custom_addons,/home/amir/erpProject/oca_addons/reporting-engine,/home/amir/erpProject/oca_addons/server-ux,/home/amir/erpProject/oca_addons/account-financial-reporting
admin_passwd = $pbkdf2-sha512$600000$MEYoBYDwPgcgZAzhPAdAaA$cqZEjR7XQ4CjHgGG6V2eT9QSaKydTOAXQlxFc2pam1FFNsDZ8F5N.CQ7zPR7uc7XKJR7rpnr8gwggCbqhsOOMg
workers = 0
max_cron_threads = 1
logfile = /home/amir/erpProject/odoo.log
data_dir = /home/amir/erpProject/data
limit_time_cpu = 600
limit_time_real = 1200
