{
    'name': 'Reema Purchase',
    'version': '18.0.1.0.0',
    'category': 'Purchase',
    'summary': 'Custom Purchase Orders, Inward Gate Pass, GRN, and Vendor Bill Matching',
    'depends': ['purchase', 'stock', 'stock_account', 'account', 'reema_mrp', 'reema_accounting'],
    'data': [
        'security/reema_purchase_security.xml',
        'security/ir.model.access.csv',
        'security/reema_account_move_rules.xml',
        'data/ir_sequence_data.xml',
        'data/account_data.xml',
        'views/product_views.xml',
        'views/reema_purchase_order_views.xml',
        'views/reema_gate_pass_views.xml',
        'views/reema_ilo_outward_pass_views.xml',
        'views/reema_grn_views.xml',
        'views/vendor_bill_views.xml',
        'views/menu_views.xml',
        'report/po_report.xml',
        'report/grn_report.xml',
        'report/vendor_bill_report.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'reema_purchase/static/src/views/po_list_view.js',
            'reema_purchase/static/src/js/open_partner_new_tab.js',
            'reema_purchase/static/src/xml/open_partner_new_tab.xml',
            'reema_purchase/static/src/js/grn_gate_pass_tags_readonly.js',
        ],
    },
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}
