{
    'name': 'Reema Purchase',
    'version': '18.0.1.0.0',
    'category': 'Purchase',
    'summary': 'Custom Purchase Orders, Inward Gate Pass, GRN, and Bill Matching',
    'depends': ['purchase', 'stock', 'stock_account', 'account', 'reema_mrp', 'reema_accounting'],
    'data': [
        'security/reema_purchase_security.xml',
        'security/ir.model.access.csv',
        'data/ir_sequence_data.xml',
        'data/account_data.xml',
        'views/product_views.xml',
        'views/reema_purchase_order_views.xml',
        'views/reema_gate_pass_views.xml',
        'views/reema_grn_views.xml',
        'views/reema_bill_matching_views.xml',
        'views/menu_views.xml',
        'report/po_report.xml',
        'report/grn_report.xml',
    ],
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}
