{
    'name': 'Reema Accounting',
    'version': '18.0.1.0.5',
    'category': 'Accounting',
    'summary': 'Chart of Accounts, Taxes, and Journals for Reema Tec',
    'depends': ['account', 'stock_account', 'purchase_stock', 'account_financial_report', 'reema_mrp', 'reema_invoice', 'account_payment', 'account_edi_ubl_cii'],
    'data': [
        'security/ir.model.access.csv',
        'security/reema_apps_access.xml',
        'security/reema_accounting_security.xml',
        'security/reema_account_move_rules.xml',
        'report/coa_report.xml',
        'report/general_ledger_report_inherit.xml',
        'report/financial_report_print_button.xml',
        'views/reema_contractor_bill_approval_views.xml',
        'views/reema_contractor_bill_report.xml',
        'views/reema_contractor_views.xml',
        'views/reema_contractor_advance_views.xml',
        'views/reema_contractor_advance_report.xml',
        'views/reema_payment_voucher_report.xml',
        'views/reema_vendor_balance_report.xml',
        'views/reema_customer_balance_report.xml',
        'views/reema_contractor_balance_report.xml',
        'views/account_menu_views.xml',
        'views/reema_cash_bank_voucher_views.xml',
        'views/reema_ledger_views.xml',
        'data/account_group_data.xml',
        'data/account_account_data.xml',
        'data/account_tax_data.xml',
        'data/account_journal_data.xml',
        'data/account_category_data.xml',
        'data/ir_sequence_data.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'reema_accounting/static/src/js/contractor_bill_delete_last_line.js',
            'reema_accounting/static/src/js/zero_dash_monetary_field.js',
        ],
    },
    'installable': True,
    'application': True,
    'auto_install': False,
    'post_init_hook': 'post_init_hook',
}
