{
    'name': 'Reema Group MRP',
    'version': '2.7',
    'category': 'Manufacturing',
    'summary': 'Integrated MRP flow for Football Production (Reema Group Logic)',
    'description': """
        Integrates the 17-Hall production flow into Odoo's standard Manufacturing Orders.
        Includes contractor assignment, batch progress tracking, and SFG inventory movement.
    """,
    'author': 'Gemini CLI',
    'depends': ['mrp', 'stock', 'account', 'analytic', 'purchase', 'reema_invoice'],
    'data': [
        'security/reema_mrp_security.xml',
        'security/ir.model.access.csv',
        'data/ir_sequence_data.xml',
        'views/report_layout_inherit.xml',
        'views/mrp_views.xml',
        'views/reema_piece_rate_views.xml',
        'views/reema_piece_rate_report.xml',
        'views/reema_bom_report.xml',
        'views/reema_mo_report.xml',
        'views/reema_production_order_views.xml',
        'views/reema_material_requirement_views.xml',
        'views/reema_wo_batch_views.xml',
        'views/reema_material_issuance_views.xml',
        'views/reema_material_issuance_report.xml',
        'views/reema_consumable_issuance_views.xml',
        'views/reema_consumable_return_views.xml',
        'views/reema_ilo_views.xml',
        'views/reema_contractor_status_views.xml',
        'views/product_list_views.xml',
        'views/reema_products_report.xml',
        'views/res_users_views.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'reema_mrp/static/src/components/wo_list_styles.css',
            'reema_mrp/static/src/components/wo_list_dropdown_patch.xml',
            'reema_mrp/static/src/components/many2one_no_create_patch.js',
            'reema_mrp/static/src/components/info_banner.js',
            'reema_mrp/static/src/components/info_banner.xml',
            'reema_mrp/static/src/components/mo_confirm_banner.js',
            'reema_mrp/static/src/components/mo_confirm_banner.xml',
            'reema_mrp/static/src/views/workorder_standalone_list_view.js',
            'reema_mrp/static/src/views/workorder_completed_nav_list.js',
            'reema_mrp/static/src/views/workorder_completed_nav_list.css',
            'reema_mrp/static/src/views/move_one2many_no_detail.js',
            'reema_mrp/static/src/components/panels_balls_sync_field.js',
            'reema_mrp/static/src/components/trim_float_field.js',
            'reema_mrp/static/src/components/piece_rate_m2o.js',
            'reema_mrp/static/src/components/many2one_new_tab.js',
            'reema_mrp/static/src/stock_ledger/stock_ledger.js',
            'reema_mrp/static/src/stock_ledger/stock_ledger.xml',
            'reema_mrp/static/src/views/product_name_nav_list.js',
            'reema_mrp/static/src/views/product_name_nav_list.xml',
            'reema_mrp/static/src/views/product_name_nav_list.css',
        ],
    },
    'post_init_hook': 'post_init_hook',
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}
