{
    'name': 'Reema HR',
    'version': '18.0.1.0.73',
    'category': 'Human Resources',
    'summary': 'Attendance, Salary Advances, Employee Loans and Payroll for Reema Tec',
    'description': """
        HR module covering employee lifecycle (hiring/firing/quitting via core HR),
        daily attendance with late-arrival deduction, salary advances, employee
        loans with installment recovery, and monthly payslips posted to Accounting.
    """,
    'author': 'Reema Tec',
    'depends': ['hr', 'reema_accounting'],
    'data': [
        'security/reema_hr_security.xml',
        'security/ir.model.access.csv',
        'data/ir_sequence_data.xml',
        'views/res_company_views.xml',
        'views/hr_employee_views.xml',
        'views/reema_hr_attendance_views.xml',
        'views/reema_hr_public_holiday_views.xml',
        'views/reema_hr_employee_advance_views.xml',
        'views/reema_hr_payslip_views.xml',
        'views/reema_hr_payslip_accounts_views.xml',
        'views/reema_payroll_balance_views.xml',
        'views/reema_hr_payslip_report.xml',
        'views/reema_hr_payslip_list_report.xml',
        'views/reema_hr_menus.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'reema_hr/static/src/css/attendance_list_styles.css',
            'reema_hr/static/src/js/attendance_date_range_list.js',
            'reema_hr/static/src/js/attendance_date_range_list.xml',
            'reema_hr/static/src/js/many2one_new_tab.js',
            'reema_hr/static/src/js/account_ledger_link_field.js',
            'reema_hr/static/src/js/account_ledger_link_field.xml',
            'reema_hr/static/src/js/save_first_button.js',
            'reema_hr/static/src/js/payslip_month_filter_list.js',
            'reema_hr/static/src/js/payslip_month_filter_list.xml',
            'reema_hr/static/src/js/advance_month_filter_list.js',
            'reema_hr/static/src/js/advance_month_filter_list.xml',
        ],
    },
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}
